name: checkin_yxyapp

on:
  
  #push: # push触发
  #  branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '30 13,22 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
    
jobs:
  yxyapp:
    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-latest
    
    steps:   
    # 检出
    #- name: Checkout
    #  uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Run yxyapp
      run: |
         docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         docker-compose up --no-build --force-recreate --detach jd1
         docker ps 
         docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; yxyPhone="${{secrets.YXYPHONE}}";  node yxyapp.js'
